# Dependencies

# Permalinks
permalink:        /:title
remote_theme: poole/hyde
#relative_permalinks: true

# Setup
title:            Will Jobs
#tagline:          'A Jekyll theme'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://willjobs.com
baseurl:          /blog

author:
  name:           'Will Jobs'
  url:            https://willjobs.com

social:
  name: Will Jobs
  links:
    - https://www.linkedin.com/in/willjobs
    - https://github.com/willjobs

paginate:         5

sass:
    style: compressed

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/willjobs

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
